[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.19.0"
minifb = "0.26.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"